# Generated by Django 2.2.4 on 2021-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all',
        ),
    ]
