# Generated by Django 2.2.4 on 2021-05-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='book',
            new_name='book1',
        ),
    ]
